parameters:
- name: name  # defaults for any parameters that aren't specified
  default: ''
- name: vmImage
  default: 'ubuntu-latest'

jobs:
- job: ${{ parameters.name }}
  pool: 
    vmImage: ${{ parameters.vmImage }}
  steps:
  - script: apt install nodejs
  - script: node -v
